# SPDX-License-Identifier: GPL-2.0
vimc-y := vimc-core.o vimc-common.o vimc-streamer.o vimc-capture.o \
		vimc-debayer.o vimc-scaler.o vimc-sensor.o vimc-lens.o \
		vimc-sensor-hsi16.o

obj-$(CONFIG_VIDEO_VIMC) += vimc.o

